### ISSUE TITLE
[BUG] Notepad.jar missing

### ISSUE THREAD

**Issue by huntergt116** [fredjt/Universal-File-Reader#4]
When I build the Java program, the build fails, citing a missing Notepad.jar file.

I imported the UFR project and the necessary libraries, and then ran the project in Eclipse.

It appears the source is on a local host, and not in the Git repo.
(/Universal File Reader/C:/Users/Home PC/OneDrive - Knights - University of Central Florida/School/Principles of Computer Programming/jdk1.8.0_241/demo/jfc/Notepad/src.zip)

Device: MacOS 10.15.5
Eclipse: 4.16.0

**Comment by fredjt** [comment]
Thank you for letting me know! 
I had removed the JAR from the build path, but Eclipse left it in the classpath, so I removed it manually. 
Please try the new pre-release ([v0.2.0](https://github.com/fredjt/Universal-File-Reader/releases/tag/v0.2.0)) and let me know if the problem is fixed.

**Comment by fredjt** [comment]
I forgot to push the changes from Eclipse before I published the second pre-release. Sorry about that. 
However, the third one ([v0.3.0](https://github.com/fredjt/Universal-File-Reader/releases/tag/v0.3.0)) is up to date. Please let me know if it still has issues. 
Thank you!
